# Generated by Django 5.2.6 on 2025-09-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='recommendation',
            new_name='recommended_action',
        ),
        migrations.RenameField(
            model_name='alert',
            old_name='event_description',
            new_name='summary_description',
        ),
    ]
