# Generated by Django 5.2.6 on 2026-04-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_port_rename_recommendation_alert_recommended_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='confidence_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='alert',
            name='estimated_cost_impact_usd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='estimated_delay_days',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alert',
            name='event_target',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='alert',
            name='event_type',
            field=models.CharField(default='Supply Risk Event', max_length=120),
        ),
        migrations.AddField(
            model_name='alert',
            name='evidence_summary',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='alert',
            name='raw_context',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='alert',
            name='risk_score',
            field=models.FloatField(default=0.0),
        ),
    ]
