from django.db import models

class Port(models.Model):
    # This is a placeholder model from the original design.
    # We can leave it for now.
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

class Alert(models.Model):
    """
    Represents a structured alert generated by the RAG pipeline.
    """
    impact_analysis = models.TextField()
    recommended_action = models.TextField()
    summary_description = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Alert for {self.summary_description} at {self.created_at}"
